
######### Productivity tools ##########

setwd("C:\\Users\\Hendrik Z\\Desktop\\R-course Harvard")

#### Section 1: Installing software #####


install.packages("dslabs")  # to install a single package
install.packages(c("tidyverse", "dslabs")) # to install two packages at the same time
installed.packages() # to see the list of all installed packages

library(tidyverse)


# Section 2: Basic Unix
# ls #list dir content
# mkdir folder_name #create directory called "folder_name"
# rmdir folder_name  #remove an empty directory as long as it is empty
# rm -r folder_name  #remove dir that is not empty, "r" stands for recursive
# cd: change dir
# ../ # two dots represents parent dir
# . # single dot represents current workingdir 
# cd ~/projects # concatenate with forward slashes
# cd ../.. # change to two parent layer beyond
# cd -  # whatever dir you were before
# cd  # return to the home dir


# mv path-to-file path-to-destination-directory
# rm filename-1 filename-2 filename-3

# less cv.tex


########### In terminal ###########
# cd ~    # move to home directory
# mkdir projects    # make a new directory called projects
# cd projects    # move to ~/projects directory
# mkdir murders    # make new directory called murders inside of projects
# cd murders    # move to ~/projects/murders/
# mkdir data rda    # make two new directories, one is data the other is rda folder
# ls    # to check if we indeed have one data folder and one rda folder
# pwd    # check the current working directory
# mkdir figs    # make a directory called figs to store figures


########## In RStudio ########
# pick existing directory as new project
# getwd()    # to confirm current working directory
# save()    # save into .rda file, .RData is also fine but less preferred
# ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"


